### ISSUE TITLE
Connection Failed: Server is not wrapping data

### ISSUE THREAD

**Issue by Ji3jin** [ContinuumIO/libhdfs3-downstream#17]
I re-compiled this program with protobuf 2.5 version.
when I use hdfs3 with libhdfs3 I found the error.
```
[root@datanode-2 ~]# python
Python 2.7.13 |Anaconda custom (64-bit)| (default, Dec 20 2016, 23:09:15) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import ctypes as ct
>>> ct.cdll.LoadLibrary('libhdfs3.so')
<CDLL 'libhdfs3.so', handle 1e1d270 at 7f9c1c76ce90>
>>> from hdfs3 import HDFileSystem
>>> client = HDFileSystem(host='namenode-1',port=9000,ticket_cache='/tmp/krb5cc_0')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/gavial-anaconda2/lib/python2.7/site-packages/hdfs3/core.py", line 75, in __init__
    self.connect()
  File "/usr/local/gavial-anaconda2/lib/python2.7/site-packages/hdfs3/core.py", line 136, in connect
    raise ConnectionError('Connection Failed: {}'.format(msg))
hdfs3.compatibility.ConnectionError: Connection Failed: Server is not wrapping data

```

I don't know why!
```
[root@datanode-2 ~]# protoc --version
libprotoc 2.5.0
[root@datanode-2 ~]# /usr/local/gavial-anaconda2/bin/conda list|grep proto
libprotobuf               2.5.0                         0  
protobuf                  3.3.2                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xorg-kbproto              1.0.7                         1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xorg-renderproto          0.11.1                        1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xorg-xextproto            7.3.0                         1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xorg-xproto               7.0.31                        6    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
[root@datanode-2 ~]# /usr/local/gavial-anaconda2/bin/conda list|grep hdfs
hdfs3                     0.2.0                    py27_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libhdfs3                  2.3                           0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
python-hdfs               2.0.16                   py27_0    conda-forge

```

I replace the compiled package libhdfs3.so.2.2.31 to anaconda2/lib/libhdfs3.so.2.2.31

when I compile the program with other version protobuf, I get another error:
```
[root@datanode-3 ~]# python
Python 2.7.14 |Anaconda custom (64-bit)| (default, Oct 27 2017, 18:21:12) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ctypes as ct
>>> ct.cdll.LoadLibrary('libhdfs3.so')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/gavial-anaconda2/lib/python2.7/ctypes/__init__.py", line 444, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/gavial-anaconda2/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libprotobuf.so.15: cannot open shared object file: No such file or directory

```

I don't know which protobuf version is right.

**Comment by martindurant** [comment]
Any particular reason for compiling this yourself? Most people use the conda package.

Btw: this repo has become a little neglected, you might consider using pyarrow's hdfs interface instead.

**Comment by Ji3jin** [comment]
I had install hdfs3 and libhdfs3 by conda, but the libhdfs3 installed by conda not support the acl auth.
so I compile it by myself.   
Thanks for pyarrow,I will have a try!

**Comment by Ji3jin** [comment]
pyarrow works good！ Thanks a lot.
